# Change these first
owner: zhanxw # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: zhanxw main site
    url: https://zhanxw.com
  - name: Omics Rocks
    url: https://omics.rocks
  - name: gene work
    url: https://gene.work
  - name: IsoAnalytics
    url: https://cdc.biohpc.swmed.edu/isoplexis/
  - name: ScopeViewer
    url: https://cdc.biohpc.swmed.edu/scopeviewer/
  - name: QBRC main site
    url: https://qbrc.swmed.edu
  - name: VAMPr VAriant Mapping and Prediction of antimicrobial resistance 
    url: https://cdc.biohpc.swmed.edu/VAMPr/VAMPr.cgi  
  - name: Omics Rocks
    url: https://omics.rocks
  - name: MB.LRP
    url: https://cdc.biohpc.swmed.edu/mblrp/
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Service status by Zhan lab, provided by **Upptime** and GitHub."
  introMessage: This lists the main services or resources related to my research. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
